[project]
name = "mcp-deep-learning-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.78.0",
    "arxiv>=2.4.0",
    "ipykernel>=7.1.0",
    "python-dotenv>=1.2.1",
]
